language: node_js
node_js: 11
cache: yarn
addons:
  ssh_known_hosts: 198.13.42.242

before_install: openssl aes-256-cbc -K $encrypted_cb5a173d3e5c_key -iv $encrypted_cb5a173d3e5c_iv -in id_rsa.enc -out id_rsa -d
install: yarn
script: npm run build

after_success:
  - eval $(ssh-agent -s)
  - chmod 600 id_rsa
  - ssh-add id_rsa
  - git pull origin back-end --allow-unrelated-histories
  - mv api dist
  - scp -r dist/* travis@198.13.42.242:/www/wwwroot/hw.kidonng.me
